### ISSUE TITLE
Routing not suitable on production?

### ISSUE THREAD

**Issue by akawahuynh** [ultimateshadsform/astro-electron-ts#9]
![image](https://github.com/user-attachments/assets/c550d411-a68f-41d7-bbe9-b3a92bc49d51)
![image](https://github.com/user-attachments/assets/7e9a7281-e93e-4dc8-9246-4b429b64e67b)

**Comment by ultimateshadsform** [comment]
Oh sorry. Will fix.

**Comment by ultimateshadsform** [comment]
Source of problem is Astro is using Absolute links and not relative so that's why it's getting C:/ drive. Still trying to fix

**Comment by ultimateshadsform** [comment]
Should be fixed in bc77a5e.

Try version `^1.0.23`

Can you try it? I did and it works. SPA should work too.

Example with Vue 3 SPA in electron:
```jsx
// test-project\src\pages\[...all].astro
---
import Layout from '../layouts/Layout.astro';

// Add static paths for all possible routes
export function getStaticPaths() {
  return [
    { params: { all: undefined } },  // Matches /
    { params: { all: 'about' } },    // Matches /about
  ];
}
---

<Layout title="Welcome to Astro.">
  <a href="/about">About</a>
  <div id="app"></div>
</Layout>

<script>
import { createApp } from 'vue'
import { router } from '../router'
import App from '../components/App.vue'

const app = createApp(App)
app.use(router)
app.mount('#app')
</script>
```

App.vue
```vue
<template>
  <div>
    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/about">About</RouterLink>
    </nav>
    <RouterView></RouterView>
  </div>
</template>

<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';
</script>

<style scoped>
nav {
  padding: 1rem;
  text-align: center;
}

nav a {
  color: rgb(var(--accent-light));
  text-decoration: none;
  margin: 0 0.5rem;
}

nav a.router-link-active {
  text-decoration: underline;
}
</style>
```

Don't forget to make static mode:
```js
import electron from '../src/index';
// @ts-check
import { defineConfig } from 'astro/config';
import vue from '@astrojs/vue';

// https://astro.build/config
export default defineConfig({
  integrations: [electron(), vue()],
  output: 'static',
  build: {
    client: 'static'
  }
});
```

**Comment by ultimateshadsform** [comment]
Normal routing should work. But spa doesn't yet. I'm gonna try to fix that.

**Comment by ultimateshadsform** [comment]
SPA should work I tried using Vue.

In bc77a5e

Version `^1.0.24`

**Comment by ultimateshadsform** [comment]
Hm still is buggy with SPA.

**Comment by akawahuynh** [comment]
Good working!!!

![image](https://github.com/user-attachments/assets/344dcdfd-4b36-4d12-902a-eb0703572f3e)

i tried, but now it is opening a new window, very inconvenient, i want it to work with the window, can it?

i have an idea: when clicking on the a tag, call ipc navigate to that page

![image](https://github.com/user-attachments/assets/2f61e714-660b-49ce-96e2-0e57c30134cb)
![image](https://github.com/user-attachments/assets/43b8b00e-c3f1-4c14-a6e0-20568ae013fb)

**Comment by ultimateshadsform** [comment]
Hm that's really weird. It doesn't open a window for me.

I have this in my main.ts:

```ts
// electron/main.ts
import { app, BrowserWindow } from 'electron';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the directory name in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function createWindow() {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
  });

  // In development, use the Astro dev server
  if (process.env.NODE_ENV === 'development') {
    win.loadURL('http://localhost:4321');
  } else {
    // In production, load from the dist directory
    win.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  // Handle hash navigation
  win.webContents.on('will-navigate', (event, url) => {
    if (url.includes('#')) {
      event.preventDefault();
      // Extract the base URL and hash
      const [baseUrl, hash] = url.split('#');
      // Load the base page and then set the hash
      win.loadFile(path.join(__dirname, '../dist/index.html')).then(() => {
        win.webContents.executeJavaScript(`window.location.hash = '#${hash}'`);
      });
    }
  });

  // Open DevTools in development
  if (process.env.NODE_ENV === 'development') {
    win.webContents.openDevTools();
  }
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
```

**Comment by ultimateshadsform** [comment]
Could you send me the astro example so I can try it on my machine?

**Comment by ultimateshadsform** [comment]
My example isn't the best to be honest. If a user can inject in code in the hash that's not really good. I will need to find a better solution.

**Comment by akawahuynh** [comment]
I'm building it, you can follow it here
https://github.com/akawahuynh/astro-electron-test
when it's done i'll create a PR
But, does my idea make sense?

**Comment by ultimateshadsform** [comment]
Yeah I guess. This repo is just an idea? I tried to run it and it's erroring out.

**Comment by akawahuynh** [comment]
Yep, because Astro is an MPA framework, unlike Vue or React which are SPAs, that's why I had the idea of ​​creating navigation in main.ts

**Comment by ultimateshadsform** [comment]
Honestly it would probably be better to create a new Astro integration or something that makes it SPA or something. Then other and I could import it and use it.

**Comment by akawahuynh** [comment]
![image](https://github.com/user-attachments/assets/d89e25d2-541c-42f7-9dfd-39900ae008bb)
True to my idea, I created an Astro Component as a Link to route to another page.
![image](https://github.com/user-attachments/assets/04260ccb-a423-4941-9db7-6d5567989ab6)

**Comment by akawahuynh** [comment]
oh no, all my code is in the previous repo, I just review the usage with screenshots
https://github.com/akawahuynh/astro-electron-test

**Comment by ultimateshadsform** [comment]
Oh okay

**Comment by ultimateshadsform** [comment]
Error: ENOENT: no such file or directory, open 'C:\Users\shadow\Desktop\astro-electron-test\dist\routes.json'

I can't find that file

**Comment by akawahuynh** [comment]
add 
`await fs.writeFile("dist/routes.json", JSON.stringify(routes))`

into the 

> astro:build:done

 hook in your repo

![image](https://github.com/user-attachments/assets/de5582b9-4d62-488f-8a50-e4adc3b855e4)

**Comment by ultimateshadsform** [comment]
Hey COOL!!!

We might be able to use this somehow as inertia does with it's routes.

**Comment by akawahuynh** [comment]
thanks pro,
should i create a Pr or i give you the configurations

**Comment by ultimateshadsform** [comment]
Yeah. Kina like laravel Ziggy does

**Comment by ultimateshadsform** [comment]
I'm just trying to get Vue router to work. Including normal href tags etc. Might be a while.

**Comment by akawahuynh** [comment]
i see you

**Comment by ultimateshadsform** [comment]
It works in dev mode but not in building.

**Comment by akawahuynh** [comment]
if you are working with vue router

https://electron-vite.org/guide/troubleshooting#vue-router-or-react-router-dom-works-in-development-but-not-production

try this

**Comment by akawahuynh** [comment]
but why vue router 😂😂, we are working with astrojs, haha

**Comment by ultimateshadsform** [comment]
So react router and all that can work while still having astro

**Comment by akawahuynh** [comment]
Oh you mean integrating Vue router, React router, and Astro router? that seems pretty hard to do

**Comment by ultimateshadsform** [comment]
Not really. Astro acts as a server side thing while vue vue router is client side. So you get these islands. so you only have 1 astro page if you wanna do spa with Astro and react, vue etc or whatever. Or use astro itself as router etc.

**Comment by akawahuynh** [comment]
I don't understand what you mean, can you give a more specific example, because we are building the client side using astro for static build and electron for server side right? or maybe I don't understand what you mean?

**Comment by ultimateshadsform** [comment]
Example:
```jsx
---
import Layout from '../layouts/Layout.astro';
import App from '../components/App.vue';
export function getStaticPaths() {
  return [
    { params: { all: undefined } },
  ];
}
---

<Layout title="Welcome to Astro.">
  <App client:only="vue" />
</Layout>
```


To make spa you only need 1 astro route and just create a vue app, or react router app etc... and so on

**Comment by ultimateshadsform** [comment]
Then mount the app with:
```ts
// test-project\src\pages\_app.client.ts
import { router } from 'src/router';
import type { App } from 'vue';

export default (app: App) => {
  if (router) {
    app.use(router);
  }
};
``` 
etc

**Comment by ultimateshadsform** [comment]
This way any hash-mode router will work. including Astro etc. Or react, svelte or anything that Astro supports.

**Comment by akawahuynh** [comment]
of course, i understand what you mean, but the root is still astro router, and the integration of vue or react is only for state management, not router,

if routing is as you say, vue-electron or react-electron is enough, not astro-electron

https://github.com/electron-vite

**Comment by ultimateshadsform** [comment]
I managed to get it working 
![image](https://github.com/user-attachments/assets/cee4b060-0b95-4adc-b095-2de28b5705a0)

**Comment by akawahuynh** [comment]
i see you bro!!

**Comment by ultimateshadsform** [comment]
I just need to write some tests. But example:

https://github.com/user-attachments/assets/6f3e02d6-bf81-4c22-a621-088df3101a60

**Comment by ultimateshadsform** [comment]
Example

https://github.com/user-attachments/assets/d486b150-516c-42b2-b018-77e8e2f44bf4

**Comment by akawahuynh** [comment]
I think it works pretty well! What's the problem bro?

**Comment by ultimateshadsform** [comment]
I just fixed hash routing. So hash routing works.

**Comment by ultimateshadsform** [comment]
![image](https://github.com/user-attachments/assets/4fa9c89d-4ea5-40d4-b23f-baf46c6454f3)
I just tried react and it seems to work too.
